### PR TITLE
Visual mode fix and replace mode

### PR DESCRIPTION
**Pull request by simonjonathan**
Fixes cursor at the start of line when entering visual mode.
Adds replace mode detection with ModeChanged autocmd.

### CODE REVIEW

**Comment by kensleDev** [comment]
Sorry for the delay. It seems I haven't been getting notifications for this repo! And I haven't used it in quite some time.

Thanks for your contributions, I will get the new version uploaded to the package registry asap

**Comment by simonjonathan** [comment]
Didn't think this would get merged, glad you like it.
For navigating the different modes this extension worked very well for me, thanks!

I don't notice any large delays - but I don't expect good performance from writing to the config and re-rendering UI Elements.
What worked best for me is only changing the color of the cursor with `editorCursor.foreground`.

**Comment by kensleDev** [comment]
I don't have that many public projects that other people collaborate on and I think the notifications must of got lost in a sea of dependabot messages.

Agreed, it's a very hacky way of getting something like this done, but I liked the feature in VSCode Vim and had no idea how to go about this. 

I only noticed the lag on the status bar and it makes more sense for the cursor to be the default option as your eyes are already there.  I will give it a go and maybe update the README so it's the recommended config.

Thanks again for contributing!

**Comment by kensleDev** [comment]
Interestingly if I load the config in lua as is via 

```
vim.api.nvim_exec([[
...config
]])
```

I don't get the delay at all 🎉

But I do get a vscode-neovim error 😥

```
2023-03-23T19:17:36.795Z BufferManager: nvim_win_set_cursor: Cursor position outside buffer
```

Will have a play around with this and if I make any ground I will make a new release.

**Comment by simonjonathan** [comment]
I actually use the vimscript config and load it in my init.lua like this
`
prefix = os.getenv("HOME") .. '/.config/nvim'
vim.cmd('source ' .. vim.fn.expand(prefix) .. '/theme.vim')
`
not sure if that changes anything. 
But maybe it's useful for someone.

**Pull request merged**
